### ISSUE TITLE
SignIn Page after signup renders without any CSS

### ISSUE THREAD

**Issue by arvindsrinivas1** [AkashSarda3/URL-Shortner#11]
**Steps to reproduce:**

- Go to the main page and click SignUp
- Fill in the details to SignUp
- The page redirects to allow the user to SignIn. This page is rendered without any CSS. Fix this.
![Screen Shot 2022-11-29 at 9 54 08 PM](https://user-images.githubusercontent.com/10449988/204696523-9763075e-6bc6-4f51-b750-5ef9936e6485.png)

**Comment by sidhantarora** [comment]
Fixed with adding changes to sign up and sign in page
